// <auto-generated />
using CasbinTestProj;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasbinTestProj.Migrations
{
    [DbContext(typeof(CasbinDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CasbinTestProj.CasbinRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PType");

                    b.Property<string>("V0");

                    b.Property<string>("V1");

                    b.Property<string>("V2");

                    b.Property<string>("V3");

                    b.Property<string>("V4");

                    b.Property<string>("V5");

                    b.HasKey("Id");

                    b.ToTable("CasbinRule");
                });
#pragma warning restore 612, 618
        }
    }
}
